### ISSUE TITLE
Unable to pull image using file path via Firebase Storage

### ISSUE THREAD

**Issue by Techxjunkie** [comhendrik/ShopApp#3]
Are there any specifics on what file. type it needs to be or specific size?  _imagePath is not pulling from the url just spinning will in the App.

**Comment by comhendrik** [comment]
Hey, thanks for your interest. I'll check it out this weekend and comment here when I know more.

**Comment by Techxjunkie** [comment]
Ok thank you.  This is a wonderful project you have created.  I am newer to IOS app development and projects like these really help me.  Thanks

**Comment by Techxjunkie** [comment]
Hey no worries it was an error on my end.  The project is working as intended.  Also, I was able to get the virtual python server working but would this also work with another backend server like heroku?  Thanks
