### ISSUE TITLE
Heroku Backend

### ISSUE THREAD

**Issue by Techxjunkie** [comhendrik/ShopApp#4]
I was able to get the virtual python server working but would this also work with another backend server like heroku? Thanks

**Comment by comhendrik** [comment]
This should work if you host it on Heroku. I haven't tried it myself, but I use a normal HTTP request on the client side. I closed this issue because this is something that shouldn't require changes on my code.

**Comment by comhendrik** [comment]
Do you need some help with hosting it on heroku?

**Comment by Techxjunkie** [comment]
Yes,  I deployed Heroku app with secret key from Stripe however when exchanging the url with my backend server it does not event attempt a payment intent.  
I used this from Heroku to deloy

https://elements.heroku.com/buttons/jemerick-stripe/example-ios-backend
